#!/bin/bash
SCRIPT_ABS_FILENAME=`perl -e 'use Cwd "abs_path";print abs_path(shift)' "${BASH_SOURCE[0]:-${(%):-%x}}"`
SCRIPT_DIR=`dirname "$SCRIPT_ABS_FILENAME"`

cd "$SCRIPT_DIR"

. ./"Build On MacOS env" # CAREFUL : this defines SCRIPT_DIR. Works because "Build On MacOS env" and "Run with local profile" are in the same folder 

if ! [ -z $1 ]
then
    if [ "$1" = "debug" ]
    then
        CONF=debug
    else
        if [ "$1" = "release" ]
        then
            CONF=release
        else
            echo Usage : '"Build on macOS" [debug|release]'
            return 1
        fi
    fi
else
    CONF=debug
fi

./thunderbird-"$THUNDERBIRD_VERSION"/obj-thunderbird-"$CONF"/dist/Thunderbird*.app/Contents/MacOS/thunderbird -profile ./thunderbird_profile
